<Project Sdk="Aspire.AppHost.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ModuleContract/ModularSample.ModuleContract.csproj" IsAspireProjectResource="false" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Gateway/**/*.cs" />
  </ItemGroup>
</Project>
