<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Example.Preview.Producer.Contract</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Example.Preview.Shared.Contract" VersionOverride="[1.4.2]" />
  </ItemGroup>
</Project>
