<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../EShop.Modules/EShop.Modules.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../EShop.Catalog.Api/EShop.Catalog.Api.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../EShop.Orders.Api/EShop.Orders.Api.csproj" IsAspireProjectResource="false" />
  </ItemGroup>
</Project>
